### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.3.dev21+r_base_matrix

### PR DESCRIPTION
**Pull request by jdblischak**

### CODE REVIEW

**Comment by jdblischak** [comment]
The failed build on CircleCI was unexpected. The point of this PR was to build r-nhmmfdr with R 3.4.1 on osx.

Once again I suspect the Issue is changes in the defaults channel. In the build that passed when this feedstock was created, the only package pulled from defaults was libgcc:

https://circleci.com/gh/conda-forge/r-nhmmfdr-feedstock/1?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

In the currently failing build, two packages that were not included in the previous build are now pulled from defaults (libgcc-ng and libstdcxx-ng):

https://circleci.com/gh/conda-forge/r-nhmmfdr-feedstock/4?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

And the error message is:

```
gcc -std=gnu99 -shared -L/feedstock_root/build_artefacts/r-nhmmfdr_1511201655532/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/R/lib -L/feedstock_root/build_artefacts/r-nhmmfdr_1511201655532/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib -lgfortran -o NHMMfdr.so forwardbackward1.o -L/feedstock_root/build_artefacts/r-nhmmfdr_1511201655532/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/R/lib -lR
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: cannot find -lgfortran
collect2: error: ld returned 1 exit status
make: *** [NHMMfdr.so] Error 1
```

**Comment by bgruening** [comment]
I guess we need to add `libgfortran 3.0.0`?

**Comment by jdblischak** [comment]
> I guess we need to add libgfortran 3.0.0

@bgruening libgfortran is currently only available from conda-forge for osx. Adding support for Linux has been discussed and a PR submitted, but it appears to be stalled:

https://github.com/conda-forge/libgfortran-feedstock/issues/9
https://github.com/conda-forge/libgfortran-feedstock/pull/10

**Comment by dbast** [comment]
obsolete

**Pull request closed without merging**
